force-app/main/default/objects/Product_Cart__c/Product_Cart__c.object-meta.xml
<CustomObject>
    <description>A list of products to add to an Opportunity record. The cart is individual for each user.</description>
    <label>Product Cart</label>
    <nameField>
        <displayFormat>CRT-{00000000}</displayFormat>
        <label>Product Cart ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Carts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Cart__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>Parent Opportunity where we want to commit all the products from this cart.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Product Carts</relationshipLabel>
    <relationshipName>Product_Carts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/OpportunityController.cls
public with sharing class OpportunityController {
    @AuraEnabled(Cacheable=true)
    public static String getOpportunityProductCart(String opportunityID, String currentUserID) {
        // I can get the user id straight here, in Apex, but I prefer to specify it as the function's attribute for clarity and cachable
        // Id userId = UserInfo.getUserId();
        List<Product_Cart__c> productCarts = [
            SELECT
                Id
            FROM Product_Cart__c
            WHERE Opportunity__c = :opportunityID AND CreatedById = :currentUserID
            LIMIT 1
        ];
        if (productCarts.size() > 0) {
            return productCarts[0].Id;
        }
        else {
            // TODO: Create a new Cart object
            throw new AuraHandledException('ERROR: The Product Cart object for given user is not found.');
        }
    }
}