force-app/main/default/objects/Product_Cart__c/Product_Cart__c.object-meta.xml
<CustomObject>
    <description>A list of products to add to an Opportunity record. The cart is individual for each user.</description>
    <label>Product Cart</label>
    <nameField>
        <displayFormat>CRT-{00000000}</displayFormat>
        <label>Product Cart ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Carts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Cart__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>Parent Opportunity where we want to commit all the products from this cart.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Product Carts</relationshipLabel>
    <relationshipName>Product_Carts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Cart_Item__c/Product_Cart_Item__c.object-meta.xml
<CustomObject>
    <label>Product Cart Item</label>
    <nameField>
        <displayFormat>CITM-{000000000}</displayFormat>
        <label>Product Cart Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Cart Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Cart_Item__c/fields/Product_Cart__c.field-meta.xml
<CustomField>
    <fullName>Product_Cart__c</fullName>
    <label>Product Cart</label>
    <referenceTo>Product_Cart__c</referenceTo>
    <relationshipLabel>Product Cart Items</relationshipLabel>
    <relationshipName>Product_Cart_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Cart_Item__c/fields/Product_Cart_Product__c.field-meta.xml
<CustomField>
    <fullName>Product_Cart_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Cart Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Cart Items</relationshipLabel>
    <relationshipName>Product_Cart_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OpportunityProductCartController.cls
public with sharing class OpportunityProductCartController {
    @AuraEnabled(Cacheable=true)
    public static String getOpportunityProductCart(String opportunityID, String currentUserID) {
        // I can get the user id straight here, in Apex, but I prefer to specify it as the function's attribute for clarity and cachable
        // Id userId = UserInfo.getUserId();
        List<Product_Cart__c> productCarts = [
            SELECT
                Id
            FROM Product_Cart__c
            WHERE Opportunity__c = :opportunityID AND CreatedById = :currentUserID
            LIMIT 1
        ];
        if (productCarts.size() > 0) {
            return productCarts[0].Id;
        }
        else {
            // TODO: Create a new Cart object
            throw new AuraHandledException('ERROR: The Product Cart object for given user is not found.');
        }
    }

    @AuraEnabled(Cacheable=true)
    public static List<Id> getCartProducts(String productCartId) {
        List<Id> productIDs = new List<Id>();
        List<Product_Cart_Item__c> productsInCart = [
            SELECT
                Product_Cart_Product__c
            FROM Product_Cart_Item__c
            WHERE Product_Cart__c = :productCartId
        ];
        for (Product_Cart_Item__c product : productsInCart) {
            productIDs.add(product.Id);
        }
        return productIDs;
    }

    @AuraEnabled
    public static Boolean saveProductCartItemAsOpportunityItems(List<String> productCartProductIds, String opportunityId) {
        List<OpportunityLineItem> opportunityLineItems = new List<OpportunityLineItem>();
        for (String productId : productCartProductIds) {
            // TODO: more required fields?
            OpportunityLineItem opportunityItemRecord = new OpportunityLineItem(OpportunityId=opportunityId, Product2Id=productId);
            opportunityLineItems.add(opportunityItemRecord);
        }
        try {
            insert opportunityLineItems;
        }
        catch(DmlException e) {
            throw new AuraHandledException(e.getMessage());
        }
        return true;
    }
}